# named network 'dev-net' is marked as "external" (used by service 'adonisjs'), so either remove "external" from network definition or it needs to be created using: docker network create -d bridge dev-net

# named network 'dev-net' is marked as "external" (used by service 'react'), so either remove "external" from network definition or it needs to be created using: docker network create -d bridge dev-net
name: <your project name>
services:
  adonisjs:
    ports:
      - 3333:3333
    container_name: adonisjs
    networks:
      - dev-net
    image: adonisjs:1
  react:
    ports:
      - 5173:5173
    container_name: react
    networks:
      - dev-net
    image: react:1
networks:
  dev-net:
    external: true
    name: dev-net