# named network 'dev-net' is marked as "external" (used by service 'adonisjs'), so either remove "external" from network definition or it needs to be created using: docker network create -d bridge dev-net

# named network 'dev-net' is marked as "external" (used by service 'react'), so either remove "external" from network definition or it needs to be created using: docker network create -d bridge dev-net
name: alearning-project
services:
  adonisjs:
    ports:
      - 3333:3333
    container_name: adonisjs
    networks:
      - dev-net
      - backend
    image: adonisjs
    build:
      context: .
      dockerfile: ./apps/alearning-backend/Dockerfile
    depends_on:
      - mysql
    volumes:
      - .:/app/
      - /app/apps/alearning-backend/node_modules/
      - /app/apps/alearning-frontend/node_modules/
      - /app/node_modules

  react:
    ports:
      - 5173:5173
    container_name: react
    networks:
      - dev-net
    image: react
    build:
      context: .
      dockerfile: ./apps/alearning-frontend/Dockerfile
    volumes:
      - .:/app/
      - /app/apps/alearning-backend/node_modules/
      - /app/apps/alearning-frontend/node_modules/
      - /app/node_modules
    
  mysql:
    container_name: mysql-server
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_USER=alearning
      - MYSQL_PASSWORD=alearning
      - MYSQL_DATABASE=note_app
    networks:
      - backend
    image: mysql:8.0
networks:
  dev-net:
  backend: